#!/bin/sh
set -eu

# Avoid Windows-host Net-SNMP env leaking paths like C:\...
unset MIBS MIBDIRS SNMPCONFPATH || true

LISTEN_ADDRESSES="${LISTEN_ADDRESSES:-udp:0.0.0.0:162}"
TRAP_COMMUNITY="${TRAP_COMMUNITY:-public}"
TRAP_SOURCE="${TRAP_SOURCE:-}"
DISABLE_AUTH="${DISABLE_AUTH:-no}"

CONF_PATH="/etc/snmp/snmptrapd.conf"

# If a config already exists (image default or mounted), respect it.
if [ ! -f "$CONF_PATH" ] || [ "${OVERRIDE_CONFIG:-}" = "true" ]; then
  mkdir -p /etc/snmp
  {
    echo "# Generated by snmptrapd-entrypoint.sh"
    echo "agentAddress ${LISTEN_ADDRESSES}"

    if [ "$DISABLE_AUTH" = "yes" ]; then
      echo "disableAuthorization yes"
    else
      echo "disableAuthorization no"
      if [ -n "$TRAP_COMMUNITY" ]; then
        line="authCommunity log ${TRAP_COMMUNITY}"
        if [ -n "$TRAP_SOURCE" ]; then
          line="${line} ${TRAP_SOURCE}"
        fi
        echo "$line"
      fi
    fi
  } > "$CONF_PATH"
fi

exec "$@"

